### ISSUE TITLE
O consul não acha o serviço

### ISSUE THREAD

**Issue by diegosampaiorj** [thiagoloureiro/Megaphone.NetStandard#1]
Você conseguiu fazer rodar direitinho no .Net Core? Se sim, poderia mostrar, pois eu consigo subir meu serviço porém o mesmo não é encontrado pelo Consul.

**Comment by thiagoloureiro** [comment]
@diegosampaiorj primeiramente desculpe pela demora, não recebi a notificação aqui.

Acabei de testar aqui e está funcionando, vamos checar por partes o seu cenário:

**1 - Você precisa de um StatusController**, o Consul acessa esse controller para verificar se o serviço está ativo após ele se registrar.

```
[Route("status")]
    [ApiController]
    public class StatusController : ControllerBase
    {
        public string GetStatus()
        {
            Logger.Information("OK");
            return "ok";
        }
```

Resultado:
![image](https://user-images.githubusercontent.com/29433794/47942293-bd58d400-def1-11e8-930f-e5af7bbd7d1d.png)

2 - Você está rodando  o consul no Docker ou local ? Caso esteja no Docker certifique-se que o container possui acesso à sua API (para checar o status), porque normalmente o container trabalha em uma rede isolada e não acessa o host (no caso seu PC rodando a API).
Para rodar o consul localmente, faça o download no site deles, e execute:

> consul agent -dev

3 - Verifique se você fez o registro no Program.cs:

```
 public class Program
    {
        public static void Main(string[] args)
        {
            var uri = Cluster.Bootstrap(new WebApiProvider(), new ConsulProvider(), "values", "v1");
            CreateWebHostBuilder(args, uri).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args, Uri uri) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .UseUrls($"http://127.0.0.1:{uri.Port}");
    }

```

Eu fiz exatamente conforme informei aqui e está registrando normalmente no consul o serviço.
